### ISSUE TITLE
Retain line breaks

### ISSUE THREAD

**Issue by ilDon** [duffman/tspath#11]
After running `tspath` line breaks are stripped from the file and all code is on one line only. Would it be possible to retain them?

**Comment by duffman** [comment]
Yes, that would take a minor change, if this is important I could make that
option available through a command line parameter!

lör 4 aug. 2018 kl. 11:10 skrev Don <notifications@github.com>:

**Comment by duffman** [comment]
Pull version 1.3.5 and you can use "--preserve" in order to keep spaces, tabs and line breaks in the final output
