### ISSUE TITLE
outDir should be independent of baseUrl

### ISSUE THREAD

**Issue by bekker** [duffman/tspath#2]
Consider the following `tsconfig.json`.
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "outDir": "./dist",
        "baseUrl": "./src",
        "paths": {
            "core/*": ["core/*"]
        }
    },
    "exclude": [
        "node_modules",
        "dist"
    ]
}
```

outDir should be independent of baseUrl, so that resulting output directory is `projectRoot/dist`, not `projectRoot/src/dist`.

AFAIK, current implementation searchs for `projectRoot/src/dist` and throw errors.

**Comment by duffman** [comment]
Hi bekker! Thanks for your feedback! You are absolutely correct! outDir should by no means have to reflect the dist dir! The reason for this to have happened is lack of testing by that I mean it have done what it´s supposed to in my projects :) I will definitely push a fix for this asap!

**Comment by et** [comment]
Hi @duffman, any update to this?

**Comment by duffman** [comment]
Yes, I´ve had the next version running as a beta here and it will become
public this weekend :)

2018-02-22 20:42 GMT+01:00 Eric Thomas <notifications@github.com>:

**Comment by kostanev** [comment]
Same on my case. It tries to find **dist** inside **src** which is obviously wrong. It would be nice if the executable accepts parameters instead of asking runtime questions. This way the process can be automated. For example, it can be easily added as a command/task into the "scripts" section in package.json which is a common practice.

**Comment by duffman** [comment]
Yeah, I know guys, this have taken way to long to get published,
I will make a promise here, no later than this Sunday a new version
that accepts parameters will be available.

Runtime questions you can skip by using the "-f" parameter, but that
is simply an "auto yes"

2018-04-18 20:56 GMT+02:00 Damyan Kostanev <notifications@github.com>:

**Comment by jonnyasmar** [comment]
Excellent plugin! Once this issue is corrected, this should be able to handle a pretty intertwined Serverless deployment I've been trying to figure out for days. Glad I stumbled upon this :)

Looking forward to this fix!

**Comment by schani** [comment]
I'm hitting this same issue.

**Comment by ilDon** [comment]
I've created pull request #12 that fixes this issue :-)

**Comment by duffman** [comment]
Resolved in version 1.3.5

**Comment by gsusI** [comment]
Possibly back in 1.3.7?

Got 

```
project
  \
    - tsconfig.json
    - package.json
    - src\        //  code
    - build\        //  created by tsc
```

In tsconfig.json:

```bash
    "outDir": "build",
    "baseUrl": "src",
```


I'm getting the following error: 

```bash
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '<path_to_project>\src\build'
```

I'm using Windows with Node 10

**Comment by gsusI** [comment]
Ended up migrating to https://github.com/joonhocho/tscpaths, syntax is very clear, and works out-of-the-box.
