### ISSUE TITLE
Map directly to a file?

### ISSUE THREAD

**Issue by theogravity** [duffman/tspath#3]
I'm trying to do the following, but it does not seem to work:

```
    "paths": {
      "leaflet": ["./node_modules/leaflet/dist/leaflet.js"]
    }
```

The `leaflet` package does not use a minified file as its entry point. I use the standard

`import 'leaflet'` vs `import 'leaflet/dist/leaflet.js'` 

in my typescript files so I can still get type support.

I have a separate tsconfig.prod.json with the above definition so that on build, it can remap leaflet references to that.

Is there a way to do this kind of mapping?

**Comment by duffman** [comment]
Hi there mr Gravity :)
First of all, sorry for the late answer, I have been having some health issues and have been
off the grid for some time now.

To answer your question, tspath in its current release is not able to handle single files like
you describe, the upcoming version might :) I can actually see a few use cases.

//Patrik

**Comment by duffman** [comment]
After some consideration, although this feature could be "handy" at times but altogether I think it would be more confusing than useful, what this utility does is that it translates paths, what you are describing is something more of a macro-style thing and is nothing that will be implemented in the main branch!
But don´t let that stop you from forking it and having a got at it yourself!
