### ISSUE TITLE
How do I install and run this please?

### ISSUE THREAD

**Issue by bbsimonbb** [duffman/tspath#52]
I really want to get this working. The only instruction in the read me is to simply run `$ tspath`. NPM packages are not directly runnable? This is a bash prompt. Is it because I'm on windows? Do I install as a dev dependency? What then? This may sound ridiculously naive. Could the readme please be more explicit? I'm on an electron project under windows.

**Comment by edkotkas** [comment]
You can run it by either adding it to your package scripts and using `npm run <script>` or just `npx tspath` after you've installed it.

**Comment by bbsimonbb** [comment]
Super. Thanks. Closed.
